### ISSUE TITLE
URL of original project changed savannah.nongnu.org

### ISSUE THREAD

**Issue by htgoebel** [jeromerobert/pdfshuffler#12]
The original project moved from gna to https://savannah.nongnu.org/projects/pdfshuffler/

Quoting from https://sourceforge.net/p/pdfshuffler/feature-requests/36/ (2017-05-10):
> (btw the project will ultimately be moved to https://savannah.nongnu.org/projects/pdfshuffler/ instead of http://gna.org/projects/pdfshuffler/ where it is currently hosted temporarily)

**Comment by jeromerobert** [comment]
I replaced the gna.org URL by the Savannah URL in the description.

By the way, <https://savannah.nongnu.org/projects/pdfshuffler/> is still not alive so as far as I know the only place for pdfshuffler is currently this github project.
