### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by paride** [jeromerobert/pdfshuffler#14]
The port to gtk3/python3 is a huge improvement for this great tool, it is really worth a release. Many distributions (e.g. Debian) normally package only "official" releases, so the new features won't make it in the next release if a version is not tagged.

**Comment by jeromerobert** [comment]
See #9

I just e-mailed the original to known what are is plans

**Comment by jeromerobert** [comment]
Duplicate of #9 (which I just reopened)
