### ISSUE TITLE
Can't load icon. Application is not installed correctly.

### ISSUE THREAD

**Issue by steveje** [jeromerobert/pdfshuffler#3]
Hi,...

on startup pdfshuffler I get "`Can't load icon. Application is not installed correctly.`" and the icon in "Help -> Info" is not displayed. Also the issue with "`name 'file' is not defined`" happens for me too. I can't save any document.

best regards

**Comment by steveje** [comment]
Hi, still the icon in "help -> info" (about_dialog) is not displayed. 
All other problem went away,... thank you very much!

**stdout when i click "help -> info":**

`(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_scale_simple: assertion 'dest_width > 0' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_bits_per_sample: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_has_alpha: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_colorspace: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_new_from_data: assertion 'data != NULL' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_scale_simple: assertion 'dest_width > 0' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_bits_per_sample: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_has_alpha: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_colorspace: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_new_from_data: assertion 'data != NULL' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_scale_simple: assertion 'dest_width > 0' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_bits_per_sample: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_has_alpha: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_colorspace: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_new_from_data: assertion 'data != NULL' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_scale_simple: assertion 'dest_width > 0' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_bits_per_sample: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_has_alpha: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_colorspace: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_new_from_data: assertion 'data != NULL' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_scale_simple: assertion 'dest_width > 0' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_bits_per_sample: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_has_alpha: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_colorspace: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(pdfshuffler:4307): GdkPixbuf-CRITICAL **: gdk_pixbuf_new_from_data: assertion 'data != NULL' failed
`

**Comment by steveje** [comment]
Now, all the Icons are broken. (Gnome Menu, Application and the "About" Icon/Logo.) I did a clean new install. But, however the stdout-errors are away.

**Comment by steveje** [comment]
Hi,...

I just found out by accident: (I wrongly symlinked the svg, not the png file)

If i symlink the svg file, it is displayed in the "about" dialog:
`ln -s /usr/share/icons/hicolor/scalable/apps/pdfshuffler.svg /usr/share/pixmaps/pdfshuffler.svg`

If i symlink the png file, it is not displayed in the "about" dialog:
`ln -s /usr/share/icons/hicolor/48x48/apps/pdfshuffler.png /usr/share/pixmaps/pdfshuffler.png`

**Comment by jeromerobert** [comment]
I though having the icon in the `pixmaps` directory was [optional](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout). On Debian, at least, it seems to be [optional](https://wiki.debian.org/AppStream/Guidelines#Icon_best_practices). May I ask you which distribution you are using ?

Could you also provide a `strace` log where you open the about dialog ?

    strace -o pdshuffler.strace -e open,access,stat pdfshuffler

You can send it to me by e-mail if you fear it contains some confidential data.

**Comment by steveje** [comment]
Hi,...

my distribution is an fresh Arch-Linux install with Gnome 3.18.2 as desktop.
I will send you the requested strace as email.

It may be the problem here, that calling the theme and icons in Gtk3/Python3 has changed (a lot).

For instance, some lines from firewall-config:

get icon and logo:
>         (foo, width, height) = Gtk.icon_size_lookup(Gtk.IconSize.BUTTON)
        size = min(width, height)
        self.icon_theme = Gtk.IconTheme.get_default()
        try:
            self.icon = self.icon_theme.load_icon(CONFIG_NAME, size, 0)
            self.logo = self.icon_theme.load_icon(CONFIG_NAME, 48, 0)
        except:
            print(_("Failed to load icons."))
            self.icon = self.logo = None

 and the about dialog:
>         self.aboutDialog = builder.get_object("aboutDialog")
        self.aboutDialog.set_program_name(CONFIG_NAME)
        self.aboutDialog.set_version(VERSION)
        self.aboutDialog.set_authors(AUTHORS)
        self.aboutDialog.set_license(LICENSE)
        self.aboutDialog.set_wrap_license(True)
        self.aboutDialog.set_copyright(COPYRIGHT)
        self.aboutDialog.set_position(Gtk.WindowPosition.CENTER_ON_PARENT)
        self.aboutDialog.set_transient_for(self.mainWindow)
        self.aboutDialog.set_modal(True)
        self.aboutDialog.set_icon(self.icon)
        self.aboutDialog.set_logo(self.logo)
        self.aboutDialog.set_website(WEBSITE)

it appears, that firewall-config has images only in the following directories:

> ./usr/share/icons/hicolor/scalable/apps/firewall-config.svg
./usr/share/icons/hicolor/16x16/apps/firewall-config.png
./usr/share/icons/hicolor/22x22/apps/firewall-config.png
./usr/share/icons/hicolor/24x24/apps/firewall-config.png
./usr/share/icons/hicolor/32x32/apps/firewall-config.png
./usr/share/icons/hicolor/48x48/apps/firewall-config.png

best regards

**Comment by steveje** [comment]
Hi, I attached the requested strace...

2016-03-27 14:53 GMT+02:00 Jerome Robert <notifications@github.com>:

**Comment by steveje** [comment]
I haven't figured out yet, how to send a private email in Github, but anyway, here is the strace (I changed the actual username to "$USERNAME" and the hostname to "$HOSTNAME".

[pdfshuffler.strace.txt](https://github.com/jeromerobert/pdfshuffler/files/191016/pdfshuffler.strace.txt)

**Comment by jeromerobert** [comment]
Unfortunately that does not help that much. I cannot reproduce this issue so I again need your help. I just added some verbosity in 3aa9620. I get:

```
icon search path: ['/home/jerome/.local/share/icons', '/home/jerome/.icons', '/usr/share/xfce4/icons', '/usr/local/share/icons', '/usr/share/icons', '/usr/share/icons', '/usr/share/xfce4/pixmaps', '/usr/local/share/pixmaps', '/usr/share/pixmaps', '/usr/share/pixmaps', '/home/jerome/pdfshuffle/env3/share/icons']
pdf shuffler icon exists: True
-1 /home/jerome/pdfshuffle/env3/share/icons/hicolor/scalable/apps/pdfshuffler.svg
48 /home/jerome/pdfshuffle/env3/share/icons/hicolor/48x48/apps/pdfshuffler.png
```

Could you tell me what you get ?

**Comment by steveje** [comment]
I got:

> icon search path: ['/home/$USERNAME/.local/share/icons', '/home/$USERNAME/.icons', '/usr/local/share/icons', '/usr/share/icons', '/usr/local/share/pixmaps', '/usr/share/pixmaps', '/usr/share/icons']
pdf shuffler icon exists: False

**Comment by jeromerobert** [comment]
I'll setup a Arch Linux box and Gnome to see if I can reproduce this.

**Comment by jeromerobert** [comment]
The problems seems to be that `/usr/share/icons/hicolor/icon-theme.cache` must be regenerated after installing new icons. To do so just do:

    gtk-update-icon-cache /usr/share/icons/hicolor/

I guess that `firewall-config` or `meld` packages run that command.

**Comment by steveje** [comment]
Confirmed, that does the trick. Great. This can be closed then. Thank you very much!

Do you mind, splitting a beta version or so in git? Best without the inkscape commits, that you are currently working on. I like to package this for Arch.

**Comment by steveje** [comment]
Nevermind, I'll do a fork for packaging. Thank you again for your help.

**Comment by jeromerobert** [comment]
It looks like most of my commits have been integrated in the original [repo](https://gna.org/projects/pdfshuffler/ ). I'll keep updating that one for my own development. But may be you should concider using the GNA project for your package. Note that I did not check yet, that everything as been integrated.

**Comment by jeroen** [comment]
This error appears if you have compiled `gdk-pixbuf` with dynamic modules at runtime, but it can't find a required loader where it expects to find it. It can happen if you statically linked gdk-pixbuf into your application but didn't ship the loader files.

Best solution is to recompile gdk-pixbuf with all loaders embedded into the library:

    ./configure --disable-modules --with-included-loaders=yes
